name: Modelops deploy
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  repository_dispatch:
    types: [ml_ci_cd]
jobs:
  ml_ci_cd:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Python version
      run: python --version
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Download dataset
      run: wget -O data/pokedex.csv ${{github.event.client_payload.dataseturl}}
    - name: Show dataset
      run: cat data/pokedex.csv
    - name: Run Training
      run: python model/train.py
    - name: Run Tests
      run: pytest tests  # Cambiado a pytest
    - name: Build Docker image
      run: docker build -t ${{secrets.DOCKER_USER}}/${{secrets.MODEL_NAME}}:${{github.event.client_payload.sha}} .
    - name: Show Docker images
      run: docker images
    - name: Docker Login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
    - name: Docker Push
      run: docker push ${{secrets.DOCKER_USER}}/${{secrets.MODEL_NAME}}:${{github.event.client_payload.sha}}
